name: Capto
options:
  bundleIdPrefix: com.danielgamrot
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.40"

settings:
  base:
    SWIFT_VERSION: "5"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_IDENTITY: "-"
    ENABLE_HARDENED_RUNTIME: YES

targets:
  Capto:
    type: application
    platform: macOS
    sources:
      - Capto
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.danielgamrot.Capto
        INFOPLIST_FILE: Capto/Info.plist
        CODE_SIGN_ENTITLEMENTS: Capto/Capto.entitlements
        GENERATE_INFOPLIST_FILE: false
